title: Hawaiian <em>Drosophila</em> Genomes Project
description: Research on Hawaiian fruit fly genomics
theme: minima
url: "https://shchurch.github.io"
baseurl: "/Hawaiian-Drosophila-Genomes-Project"
github_url: "https://github.com/shchurch/Hawaiian-Drosophila-Genomes-Project"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-scholar

scholar:
  style: apa
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibliography

# Collections
collections:
  team:
    output: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
